/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Anniversary {
  'anniversaryType' : AnniversaryType,
  'address' : [] | [string],
  'targetYear' : bigint,
  'parishionerId' : bigint,
  'anniversaryNumber' : bigint,
  'lastName' : string,
  'eventYear' : bigint,
  'firstName' : string,
}
export interface AnniversaryPdfExport {
  'year' : bigint,
  'anniversaries' : Array<Anniversary>,
}
export type AnniversaryType = { 'baptism' : null } |
  { 'marriage' : null } |
  { 'funeral' : null };
export interface BudgetTransaction {
  'uid' : UniqueId,
  'relatedParishioner' : [] | [bigint],
  'type' : TransactionType,
  'description' : string,
  'timestamp' : bigint,
  'category' : string,
  'amount' : bigint,
  'relatedLocality' : [] | [string],
}
export interface CollectiveOffering {
  'id' : UniqueId,
  'year' : bigint,
  'description' : string,
  'timestamp' : bigint,
  'amount' : bigint,
  'locality' : string,
}
export interface Event {
  'uid' : UniqueId,
  'tasks' : Array<Task>,
  'title' : string,
  'description' : string,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FamilyMember {
  'relationType' : RelationType,
  'name' : string,
  'sacraments' : Sacraments,
}
export interface GetAnniversariesPdfExportRequest {
  'anniversaryType' : [] | [AnniversaryType],
  'year' : bigint,
}
export interface GetAnniversariesRequest {
  'anniversaryType' : [] | [AnniversaryType],
  'page' : [] | [bigint],
  'year' : bigint,
  'pageSize' : [] | [bigint],
}
export interface IndividualOffering {
  'id' : UniqueId,
  'year' : bigint,
  'description' : string,
  'timestamp' : bigint,
  'parishionerId' : bigint,
  'amount' : bigint,
}
export interface Letter {
  'uid' : bigint,
  'title' : string,
  'body' : string,
  'date' : bigint,
  'year' : bigint,
  'number' : bigint,
}
export interface Locality {
  'tasks' : Array<string>,
  'name' : string,
  'contactPerson' : string,
  'phone' : string,
}
export interface LocalityResident {
  'relationType' : [] | [RelationType],
  'name' : string,
  'isFamilyMember' : boolean,
}
export interface LocalityWithParishioners {
  'residents' : Array<LocalityResident>,
  'tasks' : Array<string>,
  'name' : string,
  'contactPerson' : string,
  'totalParishioners' : bigint,
  'phone' : string,
}
export interface Offer {
  'year' : bigint,
  'description' : string,
  'amount' : bigint,
}
export interface PaginatedResult {
  'data' : Array<StatisticEntry>,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'pageCount' : bigint,
}
export interface PaginatedResult_1 {
  'data' : Array<Parishioner>,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'pageCount' : bigint,
}
export interface PaginatedResult_10 {
  'data' : Array<BudgetTransaction>,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'pageCount' : bigint,
}
export interface PaginatedResult_11 {
  'data' : Array<Anniversary>,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'pageCount' : bigint,
}
export interface PaginatedResult_2 {
  'data' : Array<ParishNote>,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'pageCount' : bigint,
}
export interface PaginatedResult_3 {
  'data' : Array<ParishFunctionLocalityAssignment>,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'pageCount' : bigint,
}
export interface PaginatedResult_4 {
  'data' : Array<ParishFunctionAssignment>,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'pageCount' : bigint,
}
export interface PaginatedResult_5 {
  'data' : Array<LocalityWithParishioners>,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'pageCount' : bigint,
}
export interface PaginatedResult_6 {
  'data' : Array<Locality>,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'pageCount' : bigint,
}
export interface PaginatedResult_7 {
  'data' : Array<IndividualOffering>,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'pageCount' : bigint,
}
export interface PaginatedResult_8 {
  'data' : Array<Event>,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'pageCount' : bigint,
}
export interface PaginatedResult_9 {
  'data' : Array<CollectiveOffering>,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'pageCount' : bigint,
}
export interface ParishFunctionAssignment {
  'uid' : UniqueId,
  'assignedParishioner' : bigint,
  'title' : string,
  'contacts' : Array<string>,
  'description' : string,
  'address' : string,
}
export interface ParishFunctionLocalityAssignment {
  'uid' : UniqueId,
  'contacts' : Array<string>,
  'localityName' : string,
  'description' : string,
  'assignedParishioners' : Array<bigint>,
}
export interface ParishNote {
  'title' : string,
  'content' : string,
  'timestamp' : bigint,
}
export interface Parishioner {
  'uid' : bigint,
  'birthYear' : [] | [bigint],
  'profession' : [] | [string],
  'offers' : Array<Offer>,
  'email' : [] | [string],
  'pastoralNotes' : [] | [string],
  'address' : [] | [string],
  'sacraments' : Sacraments,
  'phone' : [] | [string],
  'photo' : [] | [ExternalBlob],
  'lastName' : string,
  'family' : Array<FamilyMember>,
  'firstName' : string,
}
export type RelationType = { 'other' : null } |
  { 'child' : null } |
  { 'spouse' : null };
export interface Sacraments {
  'confirmationYear' : [] | [bigint],
  'funeralYear' : [] | [bigint],
  'marriageYear' : [] | [bigint],
  'communionYear' : [] | [bigint],
  'birthYear' : [] | [bigint],
  'baptismYear' : [] | [bigint],
}
export interface StatisticEntry {
  'communionCount' : bigint,
  'timestamp' : bigint,
  'sundayAttendance' : bigint,
}
export interface Task {
  'description' : string,
  'assignedParishioners' : Array<bigint>,
}
export type TransactionType = { 'expense' : null } |
  { 'income' : null };
export type UniqueId = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBudgetTransaction' : ActorMethod<[BudgetTransaction], UniqueId>,
  'addCollectiveOffering' : ActorMethod<[CollectiveOffering], UniqueId>,
  'addEvent' : ActorMethod<[Event], UniqueId>,
  'addIndividualOffering' : ActorMethod<[IndividualOffering], UniqueId>,
  'addLetter' : ActorMethod<[string, string, bigint], bigint>,
  'addLocality' : ActorMethod<[Locality], undefined>,
  'addParishFunctionAssignment' : ActorMethod<
    [ParishFunctionAssignment],
    UniqueId
  >,
  'addParishFunctionLocalityAssignment' : ActorMethod<
    [ParishFunctionLocalityAssignment],
    UniqueId
  >,
  'addParishNote' : ActorMethod<[ParishNote], UniqueId>,
  'addParishioner' : ActorMethod<[Parishioner], bigint>,
  'addStatisticEntry' : ActorMethod<[StatisticEntry], UniqueId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBudgetTransaction' : ActorMethod<[UniqueId], undefined>,
  'deleteCollectiveOffering' : ActorMethod<[UniqueId], undefined>,
  'deleteEvent' : ActorMethod<[UniqueId], undefined>,
  'deleteIndividualOffering' : ActorMethod<[UniqueId], undefined>,
  'deleteLetter' : ActorMethod<[bigint], undefined>,
  'deleteLocality' : ActorMethod<[string], undefined>,
  'deleteParishFunctionAssignment' : ActorMethod<[UniqueId], undefined>,
  'deleteParishFunctionLocalityAssignment' : ActorMethod<[UniqueId], undefined>,
  'deleteParishNote' : ActorMethod<[UniqueId], undefined>,
  'deleteParishioner' : ActorMethod<[bigint], undefined>,
  'deleteStatisticEntry' : ActorMethod<[UniqueId], undefined>,
  'getAllCollectiveOfferings' : ActorMethod<[], Array<CollectiveOffering>>,
  'getAllIndividualOfferings' : ActorMethod<[], Array<IndividualOffering>>,
  'getAllLetters' : ActorMethod<[], Array<Letter>>,
  'getAllPaginatedParishFunctionData' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    {
      'assignments' : PaginatedResult_4,
      'localityAssignments' : PaginatedResult_3,
    }
  >,
  'getAllResidents' : ActorMethod<[], Array<LocalityResident>>,
  'getAnniversariesForYearPaginated' : ActorMethod<
    [GetAnniversariesRequest],
    PaginatedResult_11
  >,
  'getAnniversariesForYearPdfExport' : ActorMethod<
    [GetAnniversariesPdfExportRequest],
    AnniversaryPdfExport
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollectiveOffering' : ActorMethod<[UniqueId], [] | [CollectiveOffering]>,
  'getCollectiveOfferingsByLocality' : ActorMethod<
    [string],
    Array<CollectiveOffering>
  >,
  'getIndividualOffering' : ActorMethod<[UniqueId], [] | [IndividualOffering]>,
  'getIndividualOfferingsByParishioner' : ActorMethod<
    [bigint],
    Array<IndividualOffering>
  >,
  'getLetter' : ActorMethod<[bigint], [] | [Letter]>,
  'getOverallBudgetBalance' : ActorMethod<[], bigint>,
  'getPaginatedBudgetTransactions' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedResult_10
  >,
  'getPaginatedBudgetTransactionsByDateRange' : ActorMethod<
    [[] | [bigint], [] | [bigint], bigint, bigint],
    PaginatedResult_10
  >,
  'getPaginatedCollectiveOfferings' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedResult_9
  >,
  'getPaginatedEvents' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedResult_8
  >,
  'getPaginatedIndividualOfferings' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedResult_7
  >,
  'getPaginatedLocalities' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedResult_6
  >,
  'getPaginatedLocalitiesWithParishioners' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedResult_5
  >,
  'getPaginatedParishFunctionAssignments' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedResult_4
  >,
  'getPaginatedParishFunctionLocalityAssignments' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedResult_3
  >,
  'getPaginatedParishNotes' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedResult_2
  >,
  'getPaginatedParishioners' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedResult_1
  >,
  'getPaginatedStatisticEntries' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedResult
  >,
  'getResidentCountByLocality' : ActorMethod<[string], bigint>,
  'getResidentsByLocality' : ActorMethod<[string], Array<LocalityResident>>,
  'getTotalResidentCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasParishioners' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBudgetTransaction' : ActorMethod<
    [UniqueId, BudgetTransaction],
    undefined
  >,
  'updateCollectiveOffering' : ActorMethod<
    [UniqueId, CollectiveOffering],
    undefined
  >,
  'updateEvent' : ActorMethod<[UniqueId, Event], undefined>,
  'updateIndividualOffering' : ActorMethod<
    [UniqueId, IndividualOffering],
    undefined
  >,
  'updateLetter' : ActorMethod<[bigint, string, string], undefined>,
  'updateLocality' : ActorMethod<[string, Locality], undefined>,
  'updateParishFunctionAssignment' : ActorMethod<
    [UniqueId, ParishFunctionAssignment],
    undefined
  >,
  'updateParishFunctionLocalityAssignment' : ActorMethod<
    [UniqueId, ParishFunctionLocalityAssignment],
    undefined
  >,
  'updateParishNote' : ActorMethod<[UniqueId, ParishNote], undefined>,
  'updateParishioner' : ActorMethod<[bigint, Parishioner], undefined>,
  'updateStatisticEntry' : ActorMethod<[UniqueId, StatisticEntry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];