/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UniqueId = IDL.Nat;
export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const BudgetTransaction = IDL.Record({
  'uid' : UniqueId,
  'relatedParishioner' : IDL.Opt(IDL.Nat),
  'type' : TransactionType,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'amount' : IDL.Nat,
  'relatedLocality' : IDL.Opt(IDL.Text),
});
export const CollectiveOffering = IDL.Record({
  'id' : UniqueId,
  'year' : IDL.Int,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'locality' : IDL.Text,
});
export const Task = IDL.Record({
  'description' : IDL.Text,
  'assignedParishioners' : IDL.Vec(IDL.Nat),
});
export const Event = IDL.Record({
  'uid' : UniqueId,
  'tasks' : IDL.Vec(Task),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const IndividualOffering = IDL.Record({
  'id' : UniqueId,
  'year' : IDL.Int,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'parishionerId' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const Locality = IDL.Record({
  'tasks' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'phone' : IDL.Text,
});
export const ParishFunctionAssignment = IDL.Record({
  'uid' : UniqueId,
  'assignedParishioner' : IDL.Nat,
  'title' : IDL.Text,
  'contacts' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'address' : IDL.Text,
});
export const ParishFunctionLocalityAssignment = IDL.Record({
  'uid' : UniqueId,
  'contacts' : IDL.Vec(IDL.Text),
  'localityName' : IDL.Text,
  'description' : IDL.Text,
  'assignedParishioners' : IDL.Vec(IDL.Nat),
});
export const ParishNote = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Offer = IDL.Record({
  'year' : IDL.Int,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Sacraments = IDL.Record({
  'confirmationYear' : IDL.Opt(IDL.Nat),
  'funeralYear' : IDL.Opt(IDL.Nat),
  'marriageYear' : IDL.Opt(IDL.Nat),
  'communionYear' : IDL.Opt(IDL.Nat),
  'birthYear' : IDL.Opt(IDL.Nat),
  'baptismYear' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const RelationType = IDL.Variant({
  'other' : IDL.Null,
  'child' : IDL.Null,
  'spouse' : IDL.Null,
});
export const FamilyMember = IDL.Record({
  'relationType' : RelationType,
  'name' : IDL.Text,
  'sacraments' : Sacraments,
});
export const Parishioner = IDL.Record({
  'uid' : IDL.Nat,
  'birthYear' : IDL.Opt(IDL.Nat),
  'profession' : IDL.Opt(IDL.Text),
  'offers' : IDL.Vec(Offer),
  'email' : IDL.Opt(IDL.Text),
  'pastoralNotes' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'sacraments' : Sacraments,
  'phone' : IDL.Opt(IDL.Text),
  'photo' : IDL.Opt(ExternalBlob),
  'lastName' : IDL.Text,
  'family' : IDL.Vec(FamilyMember),
  'firstName' : IDL.Text,
});
export const StatisticEntry = IDL.Record({
  'communionCount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'sundayAttendance' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Letter = IDL.Record({
  'uid' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : IDL.Int,
  'year' : IDL.Nat,
  'number' : IDL.Nat,
});
export const PaginatedResult_4 = IDL.Record({
  'data' : IDL.Vec(ParishFunctionAssignment),
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'pageCount' : IDL.Nat,
});
export const PaginatedResult_3 = IDL.Record({
  'data' : IDL.Vec(ParishFunctionLocalityAssignment),
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'pageCount' : IDL.Nat,
});
export const LocalityResident = IDL.Record({
  'relationType' : IDL.Opt(RelationType),
  'name' : IDL.Text,
  'isFamilyMember' : IDL.Bool,
});
export const AnniversaryType = IDL.Variant({
  'baptism' : IDL.Null,
  'marriage' : IDL.Null,
  'funeral' : IDL.Null,
});
export const GetAnniversariesRequest = IDL.Record({
  'anniversaryType' : IDL.Opt(AnniversaryType),
  'page' : IDL.Opt(IDL.Nat),
  'year' : IDL.Nat,
  'pageSize' : IDL.Opt(IDL.Nat),
});
export const Anniversary = IDL.Record({
  'anniversaryType' : AnniversaryType,
  'address' : IDL.Opt(IDL.Text),
  'targetYear' : IDL.Nat,
  'parishionerId' : IDL.Nat,
  'anniversaryNumber' : IDL.Nat,
  'lastName' : IDL.Text,
  'eventYear' : IDL.Nat,
  'firstName' : IDL.Text,
});
export const PaginatedResult_11 = IDL.Record({
  'data' : IDL.Vec(Anniversary),
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'pageCount' : IDL.Nat,
});
export const GetAnniversariesPdfExportRequest = IDL.Record({
  'anniversaryType' : IDL.Opt(AnniversaryType),
  'year' : IDL.Nat,
});
export const AnniversaryPdfExport = IDL.Record({
  'year' : IDL.Nat,
  'anniversaries' : IDL.Vec(Anniversary),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const PaginatedResult_10 = IDL.Record({
  'data' : IDL.Vec(BudgetTransaction),
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'pageCount' : IDL.Nat,
});
export const PaginatedResult_9 = IDL.Record({
  'data' : IDL.Vec(CollectiveOffering),
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'pageCount' : IDL.Nat,
});
export const PaginatedResult_8 = IDL.Record({
  'data' : IDL.Vec(Event),
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'pageCount' : IDL.Nat,
});
export const PaginatedResult_7 = IDL.Record({
  'data' : IDL.Vec(IndividualOffering),
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'pageCount' : IDL.Nat,
});
export const PaginatedResult_6 = IDL.Record({
  'data' : IDL.Vec(Locality),
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'pageCount' : IDL.Nat,
});
export const LocalityWithParishioners = IDL.Record({
  'residents' : IDL.Vec(LocalityResident),
  'tasks' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'totalParishioners' : IDL.Nat,
  'phone' : IDL.Text,
});
export const PaginatedResult_5 = IDL.Record({
  'data' : IDL.Vec(LocalityWithParishioners),
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'pageCount' : IDL.Nat,
});
export const PaginatedResult_2 = IDL.Record({
  'data' : IDL.Vec(ParishNote),
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'pageCount' : IDL.Nat,
});
export const PaginatedResult_1 = IDL.Record({
  'data' : IDL.Vec(Parishioner),
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'pageCount' : IDL.Nat,
});
export const PaginatedResult = IDL.Record({
  'data' : IDL.Vec(StatisticEntry),
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'pageCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBudgetTransaction' : IDL.Func([BudgetTransaction], [UniqueId], []),
  'addCollectiveOffering' : IDL.Func([CollectiveOffering], [UniqueId], []),
  'addEvent' : IDL.Func([Event], [UniqueId], []),
  'addIndividualOffering' : IDL.Func([IndividualOffering], [UniqueId], []),
  'addLetter' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addLocality' : IDL.Func([Locality], [], []),
  'addParishFunctionAssignment' : IDL.Func(
      [ParishFunctionAssignment],
      [UniqueId],
      [],
    ),
  'addParishFunctionLocalityAssignment' : IDL.Func(
      [ParishFunctionLocalityAssignment],
      [UniqueId],
      [],
    ),
  'addParishNote' : IDL.Func([ParishNote], [UniqueId], []),
  'addParishioner' : IDL.Func([Parishioner], [IDL.Nat], []),
  'addStatisticEntry' : IDL.Func([StatisticEntry], [UniqueId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBudgetTransaction' : IDL.Func([UniqueId], [], []),
  'deleteCollectiveOffering' : IDL.Func([UniqueId], [], []),
  'deleteEvent' : IDL.Func([UniqueId], [], []),
  'deleteIndividualOffering' : IDL.Func([UniqueId], [], []),
  'deleteLetter' : IDL.Func([IDL.Nat], [], []),
  'deleteLocality' : IDL.Func([IDL.Text], [], []),
  'deleteParishFunctionAssignment' : IDL.Func([UniqueId], [], []),
  'deleteParishFunctionLocalityAssignment' : IDL.Func([UniqueId], [], []),
  'deleteParishNote' : IDL.Func([UniqueId], [], []),
  'deleteParishioner' : IDL.Func([IDL.Nat], [], []),
  'deleteStatisticEntry' : IDL.Func([UniqueId], [], []),
  'getAllCollectiveOfferings' : IDL.Func(
      [],
      [IDL.Vec(CollectiveOffering)],
      ['query'],
    ),
  'getAllIndividualOfferings' : IDL.Func(
      [],
      [IDL.Vec(IndividualOffering)],
      ['query'],
    ),
  'getAllLetters' : IDL.Func([], [IDL.Vec(Letter)], ['query']),
  'getAllPaginatedParishFunctionData' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [
        IDL.Record({
          'assignments' : PaginatedResult_4,
          'localityAssignments' : PaginatedResult_3,
        }),
      ],
      ['query'],
    ),
  'getAllResidents' : IDL.Func([], [IDL.Vec(LocalityResident)], ['query']),
  'getAnniversariesForYearPaginated' : IDL.Func(
      [GetAnniversariesRequest],
      [PaginatedResult_11],
      ['query'],
    ),
  'getAnniversariesForYearPdfExport' : IDL.Func(
      [GetAnniversariesPdfExportRequest],
      [AnniversaryPdfExport],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollectiveOffering' : IDL.Func(
      [UniqueId],
      [IDL.Opt(CollectiveOffering)],
      ['query'],
    ),
  'getCollectiveOfferingsByLocality' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CollectiveOffering)],
      ['query'],
    ),
  'getIndividualOffering' : IDL.Func(
      [UniqueId],
      [IDL.Opt(IndividualOffering)],
      ['query'],
    ),
  'getIndividualOfferingsByParishioner' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IndividualOffering)],
      ['query'],
    ),
  'getLetter' : IDL.Func([IDL.Nat], [IDL.Opt(Letter)], ['query']),
  'getOverallBudgetBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getPaginatedBudgetTransactions' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedResult_10],
      ['query'],
    ),
  'getPaginatedBudgetTransactionsByDateRange' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat), IDL.Int, IDL.Int],
      [PaginatedResult_10],
      ['query'],
    ),
  'getPaginatedCollectiveOfferings' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedResult_9],
      ['query'],
    ),
  'getPaginatedEvents' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedResult_8],
      ['query'],
    ),
  'getPaginatedIndividualOfferings' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedResult_7],
      ['query'],
    ),
  'getPaginatedLocalities' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedResult_6],
      ['query'],
    ),
  'getPaginatedLocalitiesWithParishioners' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedResult_5],
      ['query'],
    ),
  'getPaginatedParishFunctionAssignments' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedResult_4],
      ['query'],
    ),
  'getPaginatedParishFunctionLocalityAssignments' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedResult_3],
      ['query'],
    ),
  'getPaginatedParishNotes' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedResult_2],
      ['query'],
    ),
  'getPaginatedParishioners' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedResult_1],
      ['query'],
    ),
  'getPaginatedStatisticEntries' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedResult],
      ['query'],
    ),
  'getResidentCountByLocality' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getResidentsByLocality' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LocalityResident)],
      ['query'],
    ),
  'getTotalResidentCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasParishioners' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBudgetTransaction' : IDL.Func([UniqueId, BudgetTransaction], [], []),
  'updateCollectiveOffering' : IDL.Func([UniqueId, CollectiveOffering], [], []),
  'updateEvent' : IDL.Func([UniqueId, Event], [], []),
  'updateIndividualOffering' : IDL.Func([UniqueId, IndividualOffering], [], []),
  'updateLetter' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateLocality' : IDL.Func([IDL.Text, Locality], [], []),
  'updateParishFunctionAssignment' : IDL.Func(
      [UniqueId, ParishFunctionAssignment],
      [],
      [],
    ),
  'updateParishFunctionLocalityAssignment' : IDL.Func(
      [UniqueId, ParishFunctionLocalityAssignment],
      [],
      [],
    ),
  'updateParishNote' : IDL.Func([UniqueId, ParishNote], [], []),
  'updateParishioner' : IDL.Func([IDL.Nat, Parishioner], [], []),
  'updateStatisticEntry' : IDL.Func([UniqueId, StatisticEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UniqueId = IDL.Nat;
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const BudgetTransaction = IDL.Record({
    'uid' : UniqueId,
    'relatedParishioner' : IDL.Opt(IDL.Nat),
    'type' : TransactionType,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'amount' : IDL.Nat,
    'relatedLocality' : IDL.Opt(IDL.Text),
  });
  const CollectiveOffering = IDL.Record({
    'id' : UniqueId,
    'year' : IDL.Int,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'locality' : IDL.Text,
  });
  const Task = IDL.Record({
    'description' : IDL.Text,
    'assignedParishioners' : IDL.Vec(IDL.Nat),
  });
  const Event = IDL.Record({
    'uid' : UniqueId,
    'tasks' : IDL.Vec(Task),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const IndividualOffering = IDL.Record({
    'id' : UniqueId,
    'year' : IDL.Int,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'parishionerId' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Locality = IDL.Record({
    'tasks' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ParishFunctionAssignment = IDL.Record({
    'uid' : UniqueId,
    'assignedParishioner' : IDL.Nat,
    'title' : IDL.Text,
    'contacts' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'address' : IDL.Text,
  });
  const ParishFunctionLocalityAssignment = IDL.Record({
    'uid' : UniqueId,
    'contacts' : IDL.Vec(IDL.Text),
    'localityName' : IDL.Text,
    'description' : IDL.Text,
    'assignedParishioners' : IDL.Vec(IDL.Nat),
  });
  const ParishNote = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Offer = IDL.Record({
    'year' : IDL.Int,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Sacraments = IDL.Record({
    'confirmationYear' : IDL.Opt(IDL.Nat),
    'funeralYear' : IDL.Opt(IDL.Nat),
    'marriageYear' : IDL.Opt(IDL.Nat),
    'communionYear' : IDL.Opt(IDL.Nat),
    'birthYear' : IDL.Opt(IDL.Nat),
    'baptismYear' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const RelationType = IDL.Variant({
    'other' : IDL.Null,
    'child' : IDL.Null,
    'spouse' : IDL.Null,
  });
  const FamilyMember = IDL.Record({
    'relationType' : RelationType,
    'name' : IDL.Text,
    'sacraments' : Sacraments,
  });
  const Parishioner = IDL.Record({
    'uid' : IDL.Nat,
    'birthYear' : IDL.Opt(IDL.Nat),
    'profession' : IDL.Opt(IDL.Text),
    'offers' : IDL.Vec(Offer),
    'email' : IDL.Opt(IDL.Text),
    'pastoralNotes' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'sacraments' : Sacraments,
    'phone' : IDL.Opt(IDL.Text),
    'photo' : IDL.Opt(ExternalBlob),
    'lastName' : IDL.Text,
    'family' : IDL.Vec(FamilyMember),
    'firstName' : IDL.Text,
  });
  const StatisticEntry = IDL.Record({
    'communionCount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'sundayAttendance' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Letter = IDL.Record({
    'uid' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : IDL.Int,
    'year' : IDL.Nat,
    'number' : IDL.Nat,
  });
  const PaginatedResult_4 = IDL.Record({
    'data' : IDL.Vec(ParishFunctionAssignment),
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'pageCount' : IDL.Nat,
  });
  const PaginatedResult_3 = IDL.Record({
    'data' : IDL.Vec(ParishFunctionLocalityAssignment),
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'pageCount' : IDL.Nat,
  });
  const LocalityResident = IDL.Record({
    'relationType' : IDL.Opt(RelationType),
    'name' : IDL.Text,
    'isFamilyMember' : IDL.Bool,
  });
  const AnniversaryType = IDL.Variant({
    'baptism' : IDL.Null,
    'marriage' : IDL.Null,
    'funeral' : IDL.Null,
  });
  const GetAnniversariesRequest = IDL.Record({
    'anniversaryType' : IDL.Opt(AnniversaryType),
    'page' : IDL.Opt(IDL.Nat),
    'year' : IDL.Nat,
    'pageSize' : IDL.Opt(IDL.Nat),
  });
  const Anniversary = IDL.Record({
    'anniversaryType' : AnniversaryType,
    'address' : IDL.Opt(IDL.Text),
    'targetYear' : IDL.Nat,
    'parishionerId' : IDL.Nat,
    'anniversaryNumber' : IDL.Nat,
    'lastName' : IDL.Text,
    'eventYear' : IDL.Nat,
    'firstName' : IDL.Text,
  });
  const PaginatedResult_11 = IDL.Record({
    'data' : IDL.Vec(Anniversary),
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'pageCount' : IDL.Nat,
  });
  const GetAnniversariesPdfExportRequest = IDL.Record({
    'anniversaryType' : IDL.Opt(AnniversaryType),
    'year' : IDL.Nat,
  });
  const AnniversaryPdfExport = IDL.Record({
    'year' : IDL.Nat,
    'anniversaries' : IDL.Vec(Anniversary),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const PaginatedResult_10 = IDL.Record({
    'data' : IDL.Vec(BudgetTransaction),
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'pageCount' : IDL.Nat,
  });
  const PaginatedResult_9 = IDL.Record({
    'data' : IDL.Vec(CollectiveOffering),
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'pageCount' : IDL.Nat,
  });
  const PaginatedResult_8 = IDL.Record({
    'data' : IDL.Vec(Event),
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'pageCount' : IDL.Nat,
  });
  const PaginatedResult_7 = IDL.Record({
    'data' : IDL.Vec(IndividualOffering),
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'pageCount' : IDL.Nat,
  });
  const PaginatedResult_6 = IDL.Record({
    'data' : IDL.Vec(Locality),
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'pageCount' : IDL.Nat,
  });
  const LocalityWithParishioners = IDL.Record({
    'residents' : IDL.Vec(LocalityResident),
    'tasks' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'totalParishioners' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const PaginatedResult_5 = IDL.Record({
    'data' : IDL.Vec(LocalityWithParishioners),
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'pageCount' : IDL.Nat,
  });
  const PaginatedResult_2 = IDL.Record({
    'data' : IDL.Vec(ParishNote),
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'pageCount' : IDL.Nat,
  });
  const PaginatedResult_1 = IDL.Record({
    'data' : IDL.Vec(Parishioner),
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'pageCount' : IDL.Nat,
  });
  const PaginatedResult = IDL.Record({
    'data' : IDL.Vec(StatisticEntry),
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'pageCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBudgetTransaction' : IDL.Func([BudgetTransaction], [UniqueId], []),
    'addCollectiveOffering' : IDL.Func([CollectiveOffering], [UniqueId], []),
    'addEvent' : IDL.Func([Event], [UniqueId], []),
    'addIndividualOffering' : IDL.Func([IndividualOffering], [UniqueId], []),
    'addLetter' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'addLocality' : IDL.Func([Locality], [], []),
    'addParishFunctionAssignment' : IDL.Func(
        [ParishFunctionAssignment],
        [UniqueId],
        [],
      ),
    'addParishFunctionLocalityAssignment' : IDL.Func(
        [ParishFunctionLocalityAssignment],
        [UniqueId],
        [],
      ),
    'addParishNote' : IDL.Func([ParishNote], [UniqueId], []),
    'addParishioner' : IDL.Func([Parishioner], [IDL.Nat], []),
    'addStatisticEntry' : IDL.Func([StatisticEntry], [UniqueId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBudgetTransaction' : IDL.Func([UniqueId], [], []),
    'deleteCollectiveOffering' : IDL.Func([UniqueId], [], []),
    'deleteEvent' : IDL.Func([UniqueId], [], []),
    'deleteIndividualOffering' : IDL.Func([UniqueId], [], []),
    'deleteLetter' : IDL.Func([IDL.Nat], [], []),
    'deleteLocality' : IDL.Func([IDL.Text], [], []),
    'deleteParishFunctionAssignment' : IDL.Func([UniqueId], [], []),
    'deleteParishFunctionLocalityAssignment' : IDL.Func([UniqueId], [], []),
    'deleteParishNote' : IDL.Func([UniqueId], [], []),
    'deleteParishioner' : IDL.Func([IDL.Nat], [], []),
    'deleteStatisticEntry' : IDL.Func([UniqueId], [], []),
    'getAllCollectiveOfferings' : IDL.Func(
        [],
        [IDL.Vec(CollectiveOffering)],
        ['query'],
      ),
    'getAllIndividualOfferings' : IDL.Func(
        [],
        [IDL.Vec(IndividualOffering)],
        ['query'],
      ),
    'getAllLetters' : IDL.Func([], [IDL.Vec(Letter)], ['query']),
    'getAllPaginatedParishFunctionData' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [
          IDL.Record({
            'assignments' : PaginatedResult_4,
            'localityAssignments' : PaginatedResult_3,
          }),
        ],
        ['query'],
      ),
    'getAllResidents' : IDL.Func([], [IDL.Vec(LocalityResident)], ['query']),
    'getAnniversariesForYearPaginated' : IDL.Func(
        [GetAnniversariesRequest],
        [PaginatedResult_11],
        ['query'],
      ),
    'getAnniversariesForYearPdfExport' : IDL.Func(
        [GetAnniversariesPdfExportRequest],
        [AnniversaryPdfExport],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollectiveOffering' : IDL.Func(
        [UniqueId],
        [IDL.Opt(CollectiveOffering)],
        ['query'],
      ),
    'getCollectiveOfferingsByLocality' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CollectiveOffering)],
        ['query'],
      ),
    'getIndividualOffering' : IDL.Func(
        [UniqueId],
        [IDL.Opt(IndividualOffering)],
        ['query'],
      ),
    'getIndividualOfferingsByParishioner' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IndividualOffering)],
        ['query'],
      ),
    'getLetter' : IDL.Func([IDL.Nat], [IDL.Opt(Letter)], ['query']),
    'getOverallBudgetBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getPaginatedBudgetTransactions' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedResult_10],
        ['query'],
      ),
    'getPaginatedBudgetTransactionsByDateRange' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat), IDL.Int, IDL.Int],
        [PaginatedResult_10],
        ['query'],
      ),
    'getPaginatedCollectiveOfferings' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedResult_9],
        ['query'],
      ),
    'getPaginatedEvents' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedResult_8],
        ['query'],
      ),
    'getPaginatedIndividualOfferings' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedResult_7],
        ['query'],
      ),
    'getPaginatedLocalities' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedResult_6],
        ['query'],
      ),
    'getPaginatedLocalitiesWithParishioners' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedResult_5],
        ['query'],
      ),
    'getPaginatedParishFunctionAssignments' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedResult_4],
        ['query'],
      ),
    'getPaginatedParishFunctionLocalityAssignments' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedResult_3],
        ['query'],
      ),
    'getPaginatedParishNotes' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedResult_2],
        ['query'],
      ),
    'getPaginatedParishioners' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedResult_1],
        ['query'],
      ),
    'getPaginatedStatisticEntries' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedResult],
        ['query'],
      ),
    'getResidentCountByLocality' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getResidentsByLocality' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LocalityResident)],
        ['query'],
      ),
    'getTotalResidentCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasParishioners' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBudgetTransaction' : IDL.Func([UniqueId, BudgetTransaction], [], []),
    'updateCollectiveOffering' : IDL.Func(
        [UniqueId, CollectiveOffering],
        [],
        [],
      ),
    'updateEvent' : IDL.Func([UniqueId, Event], [], []),
    'updateIndividualOffering' : IDL.Func(
        [UniqueId, IndividualOffering],
        [],
        [],
      ),
    'updateLetter' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateLocality' : IDL.Func([IDL.Text, Locality], [], []),
    'updateParishFunctionAssignment' : IDL.Func(
        [UniqueId, ParishFunctionAssignment],
        [],
        [],
      ),
    'updateParishFunctionLocalityAssignment' : IDL.Func(
        [UniqueId, ParishFunctionLocalityAssignment],
        [],
        [],
      ),
    'updateParishNote' : IDL.Func([UniqueId, ParishNote], [], []),
    'updateParishioner' : IDL.Func([IDL.Nat, Parishioner], [], []),
    'updateStatisticEntry' : IDL.Func([UniqueId, StatisticEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };